# Generated by Django 5.2.8 on 2025-11-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='decision_runs/')),
                ('result_json', models.JSONField()),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
