# Generated by Django 5.2.8 on 2025-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_decisionanalysisrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='quant_uploads/')),
                ('y_variable', models.CharField(max_length=128)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
