# Generated by Django 5.2.8 on 2025-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_quantanalysisrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='paper_analysis/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
                ('analysis_type', models.CharField(choices=[('summary', 'Summary'), ('draft', 'Draft'), ('qa', 'Q&A'), ('system', 'System')], default='summary', max_length=10)),
                ('question', models.TextField(blank=True, null=True)),
                ('document_spec', models.JSONField(blank=True, null=True)),
                ('custom_prompt', models.TextField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
